### ISSUE TITLE
Load Images Node does not work with LCM sampler

### ISSUE THREAD

**Issue by MrForExample** [Kosinkadink/ComfyUI-VideoHelperSuite#75]
Workflow: (Load Image Node works, but Load Images Node VHS does not work)
[ImagesLoader_NotWorking.json](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/files/13453289/ImagesLoader_NotWorking.json)

**It throws out of memory when it clearly have enough memory**

>   File "C:\Users\reall\Softwares\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\container.py", line 215, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "C:\Users\reall\Softwares\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\reall\Softwares\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\reall\Softwares\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py", line 62, in forward
    return x * F.gelu(gate)
           ~~^~~~~~~~~~~~~~
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 5.76 GiB
Requested               : 915.00 MiB
Device limit            : 8.00 GiB
Free (according to CUDA): 0 bytes
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB

**Comment by MrForExample** [comment]
Turns out the LCM sampler cannot handle the large image sequences like **dpmpp_2m** can (8GB VRAM can handle 60~ images)
Reduce the number of images to load to half (30~40) solved the problem
